### ISSUE TITLE
Error: This version of %1 is not compatible with the version of Windows you’re running

### ISSUE THREAD

**Issue by HallowPrimordia** [JamzTheMan/TokenTool#16]
I apologize in advance for my noobish levels of understanding.
When I try and run the program, I keep getting this error. The installer seems to work fine, I just get this when I run the application. I am using a 32bit potato of a laptop, windows 10.

**Comment by JamzTheMan** [comment]
@HallowPrimordia Sorry, you will need a sweeter potato.

As of Java 9, x32 bit systems are no longer supportes.

With that said, there should be no reason your laptop would not support Windows x64 bit. You can try upgrading.
