### ISSUE TITLE
Programme window is invisible

### ISSUE THREAD

**Issue by FantasyPrime** [JamzTheMan/TokenTool#18]
Hi there,

Unfortunatelly I can't see anything when I launch the program.
The TokenTool is load, and after that the window doesn't show up, even if I can see it running on the tray. I can't use it this way.

Could you please come up with a solution?

Thank you

**Comment by JamzTheMan** [comment]
Can you paste the log file here? (You can drag and drop it). It will be in your user home/. tokentool-nerps directory.

I will also need version, os, and memory.
