### ISSUE TITLE
Pog filenames substitute %20 for spaces

### ISSUE THREAD

**Issue by wdmartin** [JamzTheMan/TokenTool#9]
If your portrait file name contains a space, then the Filename field under naming options hex encodes the space as %20.

![Screenshot showing the issue](https://user-images.githubusercontent.com/1242608/35188641-06bee1ea-fdff-11e7-8947-d6e934aded20.png)

This persists when the finished pog image is dragged to its destination, with the result that you have to manually correct the filename, either by changing the field before dragging the token, or by renaming the token after it's been made.

Should be a simple fix -- just use URLDecoder.decode() on the filename string before populating the Filename field.

**Comment by JamzTheMan** [comment]
Yep, will look into it.
